name: Build go-chat on Windows

on:
  push:

jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'  # 指定 Go 版本（根据项目需求调整）
          cache: true  # 启用 Go 模块缓存加速构建

      - name: Install dependencies
        run: |
          go mod tidy
          make install

      - name: Build go-chat
        run: |
          make build 
