name: Build go-chat on Windows

on:
  push:

jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Install dependencies
        run: |
          go mod tidy
          make install

      - name: Build go-chat
        run: |
          make build 

      - name: Package binary
        run: |
          $archiveName = "go-chat-windows-amd64.zip"
          Compress-Archive -Path ./bin/*.* -DestinationPath $archiveName

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          name: go-chat-windows-amd64
          tag_name: go-chat_v1.0.0
          body: |
                环境：Golang 1.23+、mysql 8.0+、Redis 5.0+、Minio(可选)
          files: /*.*
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_CHAT }}
