name: Build go-chat on Windows

on:
  push:

jobs:
  build:
    runs-on: windows-2022  # 使用 Windows Server 2022 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 拉取代码仓库

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'  # 指定 Go 版本（根据项目需求调整）
          cache: true  # 启用 Go 模块缓存加速构建

      - name: Install dependencies
        run: |
          go mod download  # 下载项目依赖

      - name: Build go-chat
        run: |
          # 设置编译参数（根据项目需求调整输出路径和名称）
          $outputName = "go-chat-windows-amd64"
          go build -o ./bin/$outputName.exe -ldflags "-s -w" ./cmd/go-chat  # 假设入口在 cmd/go-chat

      - name: Package binary
        run: |
          # 创建压缩包（包含可执行文件和必要资源）
          $archiveName = "go-chat-windows-amd64.zip"
          Compress-Archive -Path ./bin/*.exe -DestinationPath $archiveName

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: go-chat-windows-amd64.zip  # 上传打包好的文件
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动生成的 GitHub Token
